version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: eurecomendo
      POSTGRES_USER: eurecomendo
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn eurecomendo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgres://eurecomendo:password@db:5432/eurecomendo
    depends_on:
      - db

volumes:
  postgres_data:
