#!/bin/bash

echo "🔧 CONFIGURAÇÃO JWT CORRIGIDA!"
echo "=============================="

echo "📝 Passos para testar:"
echo ""
echo "1. Reiniciar o container para aplicar as mudanças:"
echo "   docker compose restart web"
echo ""
echo "2. Aguardar alguns segundos e testar o token:"
echo "   curl -X POST http://localhost:8000/api/token/ \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"username\":\"admin\",\"password\":\"admin123\"}'"
echo ""
echo "3. Se funcionar, definir o TOKEN e testar a API:"
echo "   TOKEN=\"<seu_token_aqui>\""
echo "   ./test_review_api.sh"
echo ""
echo "✅ As correções aplicadas:"
echo "   - Adicionado endpoint /api/token/ para JWT"
echo "   - Configurado SIMPLE_JWT no settings.py"
echo "   - Atualizado ReviewSerializer com campos de data"
echo "   - Adicionado permissões de autenticação"
