# Generated by Django 5.2.7 on 2025-10-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(help_text='Autor(es) do livro', max_length=255)),
                ('genre', models.CharField(blank=True, help_text='Gênero principal do livro', max_length=100)),
                ('isbn', models.CharField(blank=True, help_text='ISBN-10 ou ISBN-13', max_length=13, null=True, unique=True)),
                ('publisher', models.CharField(blank=True, help_text='Editora', max_length=255)),
                ('publication_year', models.IntegerField(blank=True, help_text='Ano de publicação', null=True)),
                ('description', models.TextField(blank=True, help_text='Sinopse do livro')),
                ('cover_url', models.URLField(blank=True, help_text='URL da imagem da capa', null=True)),
                ('page_count', models.IntegerField(blank=True, help_text='Número de páginas', null=True)),
                ('language', models.CharField(default='pt-BR', help_text='Código do idioma (ISO 639-1)', max_length=10)),
                ('categories', models.JSONField(blank=True, default=list, help_text='Lista de categorias/gêneros adicionais')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Avaliação média (0.00 a 5.00)', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='manual', help_text='Origem dos dados: manual, google_books, open_library', max_length=50)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-created_at'],
            },
        ),
    ]
