# Generated by Django 5.2.7 on 2025-10-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, help_text='URL da imagem da capa', max_length=500, null=True),
        ),
    ]
